name: 'sign in Bot'
 
on:
  watch:
    types: started
jobs:
  bot:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Set up Python 3.10.7
      uses: actions/setup-python@master
      with:
        python-version: 3.10.7
    - name: Set up Python
      uses: actions/setup-python@v2

      # 安装依赖

    - name: Install dependencies

      run: |

       python -m pip install --upgrade pip

       pip install requests
    - name: Update paper list
      run: |
        python qd.py
